# Generated by Django 5.0.4 on 2026-05-17 18:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engine_version', models.CharField(blank=True, max_length=20)),
                ('override_reason', models.TextField(blank=True, help_text='Required when the clinician selects a different facility than the engine suggested.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='DRAFT', max_length=12)),
                ('maternal_outcome', models.CharField(choices=[('survived', 'Survived'), ('died', 'Died'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('neonatal_outcome', models.CharField(choices=[('survived', 'Survived'), ('died', 'Died'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('outcome_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_referrals', to=settings.AUTH_USER_MODEL)),
                ('emergency_case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='referral', to='cases.emergencycase')),
                ('engine_recommendation', models.ForeignKey(blank=True, help_text='The facility the engine ranked #1 for this case.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engine_recommended_referrals', to='facilities.healthfacility')),
                ('receiving_facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_referrals', to='facilities.healthfacility')),
                ('referring_facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_referrals', to='facilities.healthfacility')),
            ],
            options={
                'verbose_name': 'referral',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('push', 'Push Notification'), ('email', 'Email')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='referrals.referral')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=12)),
                ('to_status', models.CharField(max_length=12)),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_status_changes', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='referrals.referral')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
