# Generated by Django 5.0.4 on 2026-07-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_referral_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='engine_mode',
            field=models.CharField(blank=True, choices=[('rule_based', 'Rule-Based'), ('ai', 'AI Analysis'), ('ai_fallback_rule_based', 'AI (fell back to rule-based)'), ('offline_rule_based', 'Rule-Based (computed offline)')], max_length=30),
        ),
    ]
