# Generated by Django 5.0.4 on 2026-05-17 00:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField(choices=[(1, 'Community / CHPS'), (2, 'Primary / District'), (3, 'Secondary / Regional'), (4, 'Tertiary / Teaching')])),
                ('district', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('available_services', models.JSONField(blank=True, default=list)),
                ('icu_beds_available', models.PositiveIntegerField(default=0)),
                ('nicu_cots_available', models.PositiveIntegerField(default=0)),
                ('theatre_available', models.BooleanField(default=False)),
                ('blood_bank', models.BooleanField(default=False)),
                ('on_call_specialist', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'health facility',
                'verbose_name_plural': 'health facilities',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'level'], name='facilities__is_acti_25fc06_idx')],
            },
        ),
        migrations.CreateModel(
            name='FacilityCapacityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot', models.JSONField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacity_changes', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_logs', to='facilities.healthfacility')),
            ],
            options={
                'verbose_name': 'capacity log entry',
                'ordering': ['-timestamp'],
            },
        ),
    ]
