# Generated by Django 5.0.4 on 2026-05-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthfacility',
            name='town',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='level',
            field=models.IntegerField(choices=[(1, 'CHPS Compound'), (2, 'Health Centre'), (3, 'District Hospital'), (4, 'Regional Hospital'), (5, 'Teaching Hospital'), (6, 'Private Facility')]),
        ),
    ]
