# Generated by Django 5.0.4 on 2026-05-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('health_worker', 'Health Worker'), ('facility_admin', 'Facility Admin'), ('specialist', 'Specialist'), ('driver', 'Driver'), ('superadmin', 'Superadmin')], default='health_worker', max_length=20),
        ),
    ]
