# Generated by Django 5.0.4 on 2026-05-22 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
        ('accounts', 'user_phone_number'),
    ]

    operations = [
    ]
