# Generated by Django 5.0.4 on 2026-05-22 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_phone_number'),
        ('accounts', 'user_expo_push_token'),
    ]

    operations = [
    ]
