# Generated by Django 5.0.4 on 2026-05-22 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20260522_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='expo_push_token',
        ),
    ]
