# Generated by Django 5.0.4 on 2026-05-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_options_alter_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('facility_admin', 'Facility Admin'), ('health_worker', 'Health Worker'), ('specialist', 'Specialist'), ('driver', 'Driver')], default='health_worker', max_length=20),
        ),
    ]
