# Generated by Django 5.0.4 on 2026-06-07 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_patient_otp_review"),
        ("accounts", "0011_otp_verification"),
    ]

    operations = []
