# Generated by Django 5.0.4 on 2026-06-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_merge_0010_patient_otp_review_0011_otp_verification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientservicereview",
            name="rating",
            field=models.PositiveSmallIntegerField(help_text="1–5 stars"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
