# Generated by Django 5.0.4 on 2026-07-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_user_expo_push_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Admin"),
                    ("facility_admin", "Facility Admin"),
                    ("health_worker", "Health Worker"),
                    ("specialist", "Specialist"),
                    ("driver", "Driver"),
                    ("patient", "Health Companion"),
                ],
                default="health_worker",
                max_length=20,
            ),
        ),
    ]
