# Generated by Django 5.0.4 on 2026-05-17 14:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('age', models.PositiveIntegerField()),
                ('district', models.CharField(blank=True, max_length=100)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('anc_visits', models.PositiveIntegerField(default=0, help_text='Number of antenatal care visits completed before this emergency.')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gestational_age_weeks', models.PositiveIntegerField(blank=True, help_text='Gestational age in completed weeks.', null=True)),
                ('gravida', models.PositiveIntegerField(blank=True, help_text='Total number of pregnancies including current.', null=True)),
                ('parity', models.PositiveIntegerField(blank=True, help_text='Number of deliveries at or beyond 20 weeks.', null=True)),
                ('obstetric_history', models.TextField(blank=True, help_text='Relevant prior complications, surgeries, or notes.')),
                ('presenting_complaint', models.TextField(help_text="Chief complaint in the health worker's own words.")),
                ('danger_signs', models.JSONField(default=list, help_text='List of recognised danger sign codes.')),
                ('vital_signs', models.JSONField(blank=True, default=dict, help_text='Keys: systolic_bp, diastolic_bp, heart_rate, respiratory_rate, temperature, spo2')),
                ('fetal_heart_rate', models.PositiveIntegerField(blank=True, help_text='Fetal heart rate in beats per minute.', null=True)),
                ('membranes_status', models.CharField(choices=[('intact', 'Intact'), ('ruptured', 'Ruptured'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
                ('referring_facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='originated_cases', to='facilities.healthfacility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.patient')),
            ],
            options={
                'verbose_name': 'emergency case',
                'verbose_name_plural': 'emergency cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TriageNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='triage_notes', to=settings.AUTH_USER_MODEL)),
                ('emergency_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_notes', to='cases.emergencycase')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emergencycase',
            index=models.Index(fields=['referring_facility', '-created_at'], name='cases_emerg_referri_9d98aa_idx'),
        ),
    ]
