# Generated by Django 5.0.4 on 2026-05-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hospital_id',
            field=models.CharField(blank=True, default='', help_text='Hospital or facility-issued patient ID / folder number.', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_name',
            field=models.CharField(blank=True, default='', help_text='Full name of the patient.', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_phone_number',
            field=models.CharField(blank=True, default='', help_text='Contact phone number for the patient or next of kin.', max_length=20),
        ),
    ]
