# Generated by Django 5.0.4 on 2026-05-28 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_patient_hospital_id_patient_patient_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='district',
            new_name='town',
        ),
    ]
