# Generated by Django 5.0.4 on 2026-06-06 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_patient_portal_anc_consent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ancvisit",
            name="concerns",
            field=models.TextField(
                blank=True, help_text="Any clinical concerns noted at this visit"
            ),
        ),
        migrations.AlterField(
            model_name="emergencycase",
            name="danger_signs",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="emergencycase",
            name="fetal_heart_rate",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emergencycase",
            name="gestational_age_weeks",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emergencycase",
            name="gravida",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emergencycase",
            name="obstetric_history",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="emergencycase",
            name="parity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emergencycase",
            name="presenting_complaint",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="emergencycase",
            name="vital_signs",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="patient",
            name="anc_visits",
            field=models.PositiveIntegerField(
                default=0, help_text="Total ANC visits (auto-updated from ANCVisit log)"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="patient_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="patient",
            name="patient_phone_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="patient",
            name="patient_user",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"role": "patient"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patient_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="risk_flags",
            field=models.JSONField(
                default=list,
                help_text="List of risk flag strings computed from history",
            ),
        ),
    ]
