# Generated by Django 5.2.16 on 2026-07-27 00:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_emergencycase_idempotency_key'),
        ('facilities', '0002_healthfacility_town_alter_healthfacility_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(choices=[('maternal', 'Maternal'), ('child', 'Child (under five)')], default='maternal', max_length=10),
        ),
        migrations.CreateModel(
            name='GrowthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_date', models.DateField()),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('muac_cm', models.FloatField(blank=True, help_text='Mid-upper arm circumference, cm', null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='growth_records', to='facilities.healthfacility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='cases.patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='growth_records_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-record_date'],
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('head_name', models.CharField(blank=True, default='', max_length=200)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('food_security_flag', models.CharField(choices=[('secure', 'Secure'), ('at_risk', 'At Risk'), ('insecure', 'Insecure'), ('unknown', 'Unknown')], default='unknown', help_text="Feeds the nutrition-guidance content engine for this household's children.", max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_households', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='households', to='facilities.healthfacility')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='cases.household'),
        ),
    ]
