# Generated by Django 6.0.7 on 2026-07-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_patient_patient_type_growthrecord_household_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='wellness_type',
            field=models.CharField(choices=[('maternal', 'Maternal'), ('wellness', 'Wellness')], default='maternal', max_length=10),
        ),
    ]
