# Generated by Django 6.0.7 on 2026-07-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_patient_wellness_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='region',
            field=models.CharField(choices=[('northern', 'Northern'), ('north_east', 'North East'), ('savannah', 'Savannah'), ('upper_east', 'Upper East'), ('upper_west', 'Upper West'), ('other', 'Other / Outside Northern Belt'), ('unknown', 'Unknown')], default='unknown', help_text='Feeds the location-aware local-food nutrition guidance.', max_length=15),
        ),
    ]
