# Generated by Django 5.0.4 on 2026-07-20 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleTrackerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_notified_date', models.DateField(blank=True, null=True)),
                ('last_notified_predicted_start', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='cycle_tracker_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wellness_cycle_tracker_state',
            },
        ),
    ]
