# Generated by Django 5.2.16 on 2026-07-27 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_patient_patient_type_growthrecord_household_and_more'),
        ('wellness', '0002_cycletrackerstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildNutritionTrackerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_notified_age_band', models.CharField(blank=True, max_length=20, null=True)),
                ('last_notified_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_tracker_state', to='cases.patient')),
            ],
            options={
                'db_table': 'wellness_child_nutrition_tracker_state',
            },
        ),
    ]
