# Generated by Django 5.0.4 on 2026-05-25 22:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transport_driver',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='facility',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('ambulance', 'Ambulance'), ('car', 'Car (Uber/Bolt/Yango)'), ('motorcycle', 'Motorcycle'), ('tricycle', 'Tricycle (Yellow-Yellow/MotorKing)'), ('truck', 'Truck'), ('other', 'Other')], default='ambulance', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='transport.driver'),
        ),
    ]
