# Generated by Django 5.0.4 on 2026-05-23 17:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('referrals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='referrals.referral')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consultations_consultation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='consultations.consultation')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consultations_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialistProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('professional_pin', models.CharField(max_length=50, unique=True)),
                ('specialty', models.CharField(choices=[('obstetrics', 'Obstetrics'), ('gynecology', 'Gynecology'), ('neonatology', 'Neonatology'), ('midwifery', 'Midwifery'), ('anaesthesiology', 'Anaesthesiology'), ('internal_medicine', 'Internal Medicine'), ('emergency_medicine', 'Emergency Medicine'), ('other', 'Other')], max_length=50)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('qualification', models.CharField(blank=True, max_length=255)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialists', to='facilities.healthfacility')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'specialist'}, on_delete=django.db.models.deletion.CASCADE, related_name='specialist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consultations_specialist_profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='consultations.specialistprofile'),
        ),
    ]
