# Generated by Django 5.0.4 on 2026-05-25 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='specialistprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='specialistprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='specialistprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='specialistprofile',
            name='specialist_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='specialistprofile',
            name='specialist_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='specialistprofile',
            name='user',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'specialist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialist_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
