# Generated by Django 6.0.7 on 2026-07-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_grandfather_approve_existing_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wellness_type',
            field=models.CharField(choices=[('maternal', 'Maternal'), ('wellness', 'Wellness')], default='maternal', max_length=20),
        ),
    ]
