# Generated by Django 5.0.4 on 2026-07-12 10:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notif_type",
                    models.CharField(
                        choices=[
                            ("referral_new", "New Referral"),
                            ("referral_status", "Referral Status Update"),
                            ("case_new", "New Emergency Case"),
                            ("patient_high_risk", "Patient Flagged High Risk"),
                            ("consultation_new", "New Consultation Request"),
                            ("consultation_status", "Consultation Status Update"),
                            ("consultation_message", "New Consultation Message"),
                            ("transport_new", "New Transport Request"),
                            ("transport_status", "Transport Status Update"),
                            ("capacity_updated", "Facility Capacity Updated"),
                            ("review_new", "New Patient Review"),
                            ("anc_visit_logged", "ANC Visit Logged"),
                            ("consent_recorded", "Consent Recorded"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField(blank=True)),
                ("url", models.CharField(blank=True, max_length=255)),
                ("related_app", models.CharField(blank=True, max_length=50)),
                ("related_id", models.CharField(blank=True, max_length=64)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("email_sent", models.BooleanField(default=False)),
                ("sms_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications_notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "-created_at"],
                        name="notificatio_recipie_684eac_idx",
                    )
                ],
            },
        ),
    ]
