# Generated by Django 5.0.4 on 2026-07-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_notif_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("referral_new", "New Referral"),
                    ("referral_status", "Referral Status Update"),
                    ("case_new", "New Emergency Case"),
                    ("patient_high_risk", "Patient Flagged High Risk"),
                    ("consultation_new", "New Consultation Request"),
                    ("consultation_status", "Consultation Status Update"),
                    ("consultation_message", "New Consultation Message"),
                    ("transport_new", "New Transport Request"),
                    ("transport_status", "Transport Status Update"),
                    ("capacity_updated", "Facility Capacity Updated"),
                    ("review_new", "New Patient Review"),
                    ("anc_visit_logged", "ANC Visit Logged"),
                    ("consent_recorded", "Consent Recorded"),
                    ("pregnancy_update", "Pregnancy Weekly Update"),
                    ("cycle_reminder", "Cycle Reminder"),
                    ("staff_approval_needed", "Staff Approval Needed"),
                    ("staff_approved", "Staff Account Approved"),
                ],
                max_length=30,
            ),
        ),
    ]
